services:
  db:
    image: postgres:17
    container_name: mayanies-postgres
    restart: always
    environment:
      POSTGRES_USER: riki
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - node_modules:/usr/src/app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile      # production Dockerfile
    container_name: mayanies-backend
    environment:
      DATABASE_URL: postgresql://riki:secret123@db:5432/mydb
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules:
