services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev   # dev Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://riki:secret123@db:5432/mydb
      PORT: 3000
